# Generated by Django 4.1.3 on 2022-11-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_brand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('In Stock', 'In stock'), ('Out Of Stoke', 'Out Of Stoke')], max_length=100, null=True),
        ),
    ]
